---
- name: Install dnsmasq
  apt: name=dnsmasq state=present

- name: remove rc
  command: update-rc.d -f dnsmasq remove removes=/etc/rc0.d/K02dnsmasq

- file: path=/etc/init.d/dnsmasq state=absent

- name: Copy dnsmasq configuration
  template: src=dnsmasq.conf dest=/etc/dnsmasq.d/dnsmasq.conf
  notify: restart dnsmasq

- name: Install dnsmasq systemd
  template: src=dnsmasq.service dest=/etc/systemd/system/dnsmasq.service
  notify: reload systemd

- name: Install dnsmasq hosts
  template: src=dnsmasq.hosts dest=/etc/dnsmasq.hosts
  notify: restart dnsmasq

- name: restart dnsmasq
  service: name=dnsmasq state=restarted

- name: reload systemd
  command: systemctl reload dnsmasq.service

